### ISSUE TITLE
Question about STT v3 async stream recognize

### ISSUE THREAD

**Issue by skinnynpale** [yandex-cloud/python-sdk#107]
Hello, I have a question about STT v3, I don’t understand how to implement asynchronous recognition in real time, I see there is an AsyncRecognizerStub, but I don’t see the RecognizeStreaming method, how is this done on v3? or should I switch to v2?

**Comment by opportunity356** [comment]
Hi! According to proto specification, there is no such method https://github.com/yandex-cloud/cloudapi/blob/master/yandex/cloud/ai/stt/v3/stt_service.proto#L29

**Comment by Noxoomo** [comment]
For real-time recognition you should use Recognizer with RecognizeStreaming method     rpc RecognizeStreaming (stream StreamingRequest) returns (stream StreamingResponse) {

**Comment by opportunity356** [comment]
> i need an async

Unfortunately, current version of python-sdk does not support python's async. In future we will add this opportunity
