### ISSUE TITLE
Exact versions of dependencies pinned in v0.296.0+

### ISSUE THREAD

**Issue by spirkaa** [yandex-cloud/python-sdk#112]
Decision to pin exact versions of dependencies in [v0.296.0](https://github.com/yandex-cloud/python-sdk/commit/a04752e37cebfb80b228fb6f3fb1882d039b19df) was unexpected.

Usually public libraries don't pin them like that to work nicely with user-defined dependencies and other libraries.

Can we undo this change?

**Comment by PeppaTheC** [comment]
Hi, we met issues with unpinned versions that dependencies are not compatible. We gonna pin on major version, is that ok for you?

**Comment by PeppaTheC** [comment]
Major versions pinned.
