### ISSUE TITLE
Relax constraint on protobuf to `<6`?

### ISSUE THREAD

**Issue by xylar** [yandex-cloud/python-sdk#121]
In #113, constraints on packages were relaxed from exact pins to just constraints on the major version.  This was a major improvement from #110, where the exact pins were introduced.

However, we are not able to update yandex-cloud beyond 2.9.5 because we have not built versions of grpcio and protobuf that fit the constraints:
```
        "grpcio>=1.64.0,<2",
        "protobuf>=4.25.3,<5",
```
It seems like the decision to pin major versions in #113 wasn't necessarily made because of known incompatibilities, at least for most packages, but rather with the thought of avoiding potential problems.  If so, would you all consider relaxing this to:
```
        "protobuf>=4.25.3,<6",
```
unless you know of specific problems with `protobuf>=5`?  This would allow us to continue to support yandex-cloud on conda-forge.

See https://github.com/conda-forge/yandexcloud-feedstock/pull/204

**Comment by xylar** [comment]
A bit more info on this.  On PyPI, everything gets statically linked so it's feasible to maintain support for protobuf 4.25.3.  On conda-forge, where packages are dynamically linked, it is prohibitive to build a giant matrix of packages that support all versions of all dependencies so we only support one version of (lib)protobuf at a time, and that is currently 5.27.5, migrating to 5.28.2.

If protobuf 5 really isn't currently supported, we will simply have to continue to refrain from updating yandex-cloud and all its dependencies until it becomes supported.

**Comment by black-roland** [comment]
I ran into a similar issue while developing an integration for Home Assistant. Home Assistant uses a specific version of protobuf ([5.28.3 currently](https://github.com/home-assistant/core/blame/2024.12.2/homeassistant/package_constraints.txt#L149)) and pip fails when I'm trying to use yandex-cloud-ml-sdl v0.3.0b3 in my integration:

```
Unable to install package yandex-cloud-ml-sdk==0.3.0b3: × No solution found when resolving dependencies:
  ╰─▶ Because yandexcloud>=0.327.0 depends on protobuf>=4.25.3,<5 and
      protobuf==5.28.3, we can conclude that yandexcloud>=0.327.0 cannot be
      used.
      And because only the following versions of yandexcloud are available:
          yandexcloud<=0.327.0
          yandexcloud==0.328.0
      we can conclude that yandexcloud>=0.327.0 cannot be used.
      And because yandex-cloud-ml-sdk==0.3.0b3 depends on yandexcloud>=0.327.0
      and you require yandex-cloud-ml-sdk==0.3.0b3, we can conclude that your
      requirements are unsatisfiable.
```

Downgrading yandex-cloud-ml-sdk to v0.1.2 works for me, but it lacks some features comparing to the latest version.

**Comment by opportunity356** [comment]
Closing this issue. If there will be any problems with new release, please tag me

**Comment by xylar** [comment]
Great, thanks!  Very much appreciated!
