### ISSUE TITLE
Vulnerable Cryptography limited by yandexcloud

### ISSUE THREAD

**Issue by potiuk** [yandex-cloud/python-sdk#131]
In airflow we are generating single set of dependencies from all providers. Yandex provider is one of them. 

Unfortunately, even the latest version of yandexcloud limits cryptography to < 3 and that prevents resolving this issue:

https://github.com/advisories/GHSA-h4gh-qq45-vh27 

Yandexcloud is the only dependency that has the limitation - allother have <45 as the least limitation.

Could you please release yandexcloud version that removes the limit ? I am considering now proposing suspention of yandexcloud provider, if that cannot be done quickly so I would appreciate somewhat fast information on the plans.

That suspension is described here ->  https://github.com/apache/airflow/blob/main/PROVIDERS.rst#suspending-releases-for-providers

**Comment by gsingh935** [comment]
@potiuk - seems like the cryptography version has already been bumped to 43.0.1 which should address the issues.
https://github.com/yandex-cloud/python-sdk/pull/127/files

**Comment by potiuk** [comment]
Fantastic. So we just need to wait until it is released ?

**Comment by opportunity356** [comment]
> So we just need to wait until it is released ?

Hi! It was released https://github.com/yandex-cloud/python-sdk/releases/tag/v0.330.0

**Comment by potiuk** [comment]
Thanks!
