### ISSUE TITLE
Поддерживаемые версии Python

### ISSUE THREAD

**Issue by max-arnold** [yandex-cloud/python-sdk#4]
Какие версии Python поддерживаются в SDK? На PyPI описание совсем пустое https://pypi.org/project/yandexcloud/, каких-то иных хинтов на версии (например, матрицы тестов) тоже навскидку найти не удалось.

Заполните плиз хотя бы classifiers в setup.py, как в ydb-python-sdk:

```
 classifiers=[
        'Programming Language :: Python',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
],
```

**Comment by MAnyKey** [comment]
Спасибо за предложение. Добавил classifiers.

**Comment by max-arnold** [comment]
И вам спасибо!
