### ISSUE TITLE
Filter by Function.name does not work in ListVersions

### ISSUE THREAD

**Issue by q0w** [yandex-cloud/python-sdk#50]
```python
client: FunctionServiceStub

client.ListVersions(ListFunctionsVersionsRequest(folder_id='...', filter='name="function1"')
```

"Bad expression at column 1. Unknown field: "name""

**Comment by q0w** [comment]
@l0kix2 not `List and ListFunctionsRequest` but [`ListVersions and ListFunctionsVersionsRequest`](https://cloud.yandex.com/en-ru/docs/functions/functions/api-ref/grpc/function_service#ListVersions)

**Comment by q0w** [comment]
So if I have `folder_id` and `function_name`, I need firstly get the current function to get `function_id` by `List and ListFunctionsRequest(folder_id='...', filter=function_name)`, and then get versions by current_function.id, because filter by function_name does not work in ListVersions.

**Comment by l0kix2** [comment]
You are correct, currently there is no way to filter versions by related function name. There is the bug in [docs](https://cloud.yandex.ru/docs/functions/functions/api-ref/grpc/function_service#ListFunctionsVersionsRequest), i'll fix it.

So for now you have to make two requests as you described:
```python
client.List(function_service_pb2.ListFunctionsRequest(folder_id="***", filter='name="function1"'))
client.ListVersions(function_service_pb2.ListFunctionsVersionsRequest(function_id="***"))
```

**Comment by q0w** [comment]
So filter in ListVersions is not working for any field?

**Comment by l0kix2** [comment]
This issue is mostly related to the yandex cloud grpc api, not SDK, so I'll close it. 
If any other questions come up, feel free to address issues to cloud support team or discuss them in our community chats.

**Comment by l0kix2** [comment]
> There is the bug in https://cloud.yandex.ru/docs/functions/functions/api-ref/grpc/function_service#ListFunctionsVersionsRequest, i'll fix it.`

Fixed
