### ISSUE TITLE
request: Type stubs

### ISSUE THREAD

**Issue by q0w** [yandex-cloud/python-sdk#53]
Would you mind adding type stubs using [nipunn1313/mypy-protobuf ](https://github.com/nipunn1313/mypy-protobuf)?

```Makefile
proto:  ## regenerate code from protobuf
	rm -rf yandex
	python3 -m grpc_tools.protoc \
        --proto_path=cloudapi \
        --proto_path=cloudapi/third_party/googleapis \
        --python_out=. \
        --grpc_python_out=. \
        --mypy_out=. \
        --mypy_grpc_out=. \
        `find cloudapi/yandex -name '*.proto'`
	find yandex -type d -exec touch {}/__init__.{py,pyi} \;

**Comment by MAnyKey** [comment]
What would be the point of adding these stubs? The point of adding standard gRPC stubs is that they are used internally in the sdk code. I see no reason to add a parallel set of stubs which won't be used.

**Comment by q0w** [comment]
They would be used outside, where the user uses python-sdk to verify types

**Comment by MAnyKey** [comment]
One can generate stubs of their own from https://github.com/yandex-cloud/cloudapi if they want.
