### ISSUE TITLE
Есть ли поддержка работы с yandex storage? 

### ISSUE THREAD

**Issue by darkAlert** [yandex-cloud/python-sdk#60]
Есть ли у этого SDK возможность работать с yandex storage?

**Comment by l0kix2** [comment]
Через SDK доступны методы BucketService https://cloud.yandex.ru/docs/storage/api-ref/grpc/bucket_service

остальные инструменты для работы с yandex storage перечислены здесь https://cloud.yandex.ru/docs/storage/tools/

**Comment by darkAlert** [comment]
Ого, есть поддержка AWS CLI. Очень хорошо. Спасибо, Кирилл!
